# Generated by Django 3.2 on 2023-02-05 09:38

import api.v1.accounts.services
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('t', 'TOP'), ('k', "KO'TARISH"), ('v', 'VIP')], max_length=1)),
                ('value', models.PositiveSmallIntegerField()),
                ('price', models.FloatField()),
                ('date_create', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(upload_to=api.v1.accounts.services.upload_tariff_path)),
                ('price', models.FloatField()),
                ('date_create', models.DateField(auto_now_add=True)),
                ('advantages', models.ManyToManyField(to='tariffs.Advantage')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True)),
                ('advantages', models.ManyToManyField(blank=True, to='tariffs.Advantage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='products.product')),
                ('tariff', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='tariffs.tariff')),
            ],
        ),
    ]
