# Generated by Django 3.2 on 2023-02-05 09:38

import api.v1.accounts.services
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_id', models.CharField(max_length=8, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=9000)),
                ('value_type', models.CharField(choices=[('n', 'Narx'), ('b', 'Bepul'), ('a', 'Ayirboshlash')], max_length=1)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('price_is_dollar', models.BooleanField(default=False)),
                ('agreement', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('business', models.BooleanField(default=False)),
                ('region', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Raqam 13 ta belgidan iborat bolishi kerak. P.s: +998912345678', regex='^+998\\d{9}$')])),
                ('auto_renewal', models.BooleanField(default=False)),
                ('views', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('y', 'Yangi'), ('j', 'Jarayonda'), ('r', 'Rad etildi'), ('t', 'Tastiqlandi')], max_length=2)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now_add=True)),
                ('main_image', models.ImageField(blank=True, upload_to=api.v1.accounts.services.upload_product_path)),
                ('image1', models.ImageField(blank=True, upload_to=api.v1.accounts.services.upload_product_path)),
                ('image2', models.ImageField(blank=True, upload_to=api.v1.accounts.services.upload_product_path)),
                ('image3', models.ImageField(blank=True, upload_to=api.v1.accounts.services.upload_product_path)),
                ('image4', models.ImageField(blank=True, upload_to=api.v1.accounts.services.upload_product_path)),
                ('image5', models.ImageField(blank=True, upload_to=api.v1.accounts.services.upload_product_path)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255)),
                ('is_true', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.field')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
