# Generated by Django 4.1.6 on 2023-02-10 03:53

import api.v1.accounts.services
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='products.category')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_fields', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_id', models.CharField(max_length=8, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('value_type', models.CharField(choices=[('p', 'price'), ('f', 'free'), ('e', 'exchange')], max_length=1)),
                ('region', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Raqam 13 ta belgidan iborat bolishi kerak. P.s: +998912345678', regex='^+998\\d{9}$')])),
                ('status', models.CharField(choices=[('n', 'new'), ('p', 'in progress'), ('r', 'rejected'), ('a', 'active')], default='n', max_length=2)),
                ('is_agreement', models.BooleanField(default=False)),
                ('price_is_dollar', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_business', models.BooleanField(default=False)),
                ('is_auto_renewal', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=9000)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('views', models.PositiveSmallIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('main_image', models.ImageField(blank=True, upload_to=api.v1.accounts.services.upload_product_path)),
                ('image1', models.ImageField(blank=True, upload_to=api.v1.accounts.services.upload_product_path)),
                ('image2', models.ImageField(blank=True, upload_to=api.v1.accounts.services.upload_product_path)),
                ('image3', models.ImageField(blank=True, upload_to=api.v1.accounts.services.upload_product_path)),
                ('image4', models.ImageField(blank=True, upload_to=api.v1.accounts.services.upload_product_path)),
                ('image5', models.ImageField(blank=True, upload_to=api.v1.accounts.services.upload_product_path)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('is_true', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productfields', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.field')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
