# Generated by Django 4.1.6 on 2023-02-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfield',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
