# Generated by Django 4.1.6 on 2023-02-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productfield_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
